Controllers/BloggController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RecipeApp.Data;
using RecipeApp.Models;
using System.Linq;
using System.Threading.Tasks;

namespace RecipeApp.Controllers
{
    public class BloggController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BloggController(ApplicationDbContext context)
        {
            _context = context;
        }

        // /Admin
        [Authorize]
        [Route("Admin")]
        public IActionResult Admin()
        {
            return View();
        }


        // GET: Blogg
        public async Task<IActionResult> Index()
        {
            return View(await _context.Blogg.OrderByDescending(x => x.CreatedDate).ToListAsync());
        }

        // .OrderByDescending(x => x.Delivery.SubmissionDate);

        // GET: Blogg/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogg = await _context.Blogg
                .FirstOrDefaultAsync(m => m.BloggId == id);
            if (blogg == null)
            {
                return NotFound();
            }

            return View(blogg);
        }

        // GET: Blogg/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogg/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BloggId,Author,Title,BloggPost,Category,CreatedDate")] Blogg blogg)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blogg);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(blogg);
        }

        // GET: Blogg/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogg = await _context.Blogg.FindAsync(id);
            if (blogg == null)
            {
                return NotFound();
            }
            return View(blogg);
        }

        // POST: Blogg/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BloggId,Author,Title,BloggPost,Category,CreatedDate")] Blogg blogg)
        {
            if (id != blogg.BloggId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blogg);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BloggExists(blogg.BloggId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(blogg);
        }

        // GET: Blogg/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogg = await _context.Blogg
                .FirstOrDefaultAsync(m => m.BloggId == id);
            if (blogg == null)
            {
                return NotFound();
            }

            return View(blogg);
        }

        // POST: Blogg/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blogg = await _context.Blogg.FindAsync(id);
            _context.Blogg.Remove(blogg);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BloggExists(int id)
        {
            return _context.Blogg.Any(e => e.BloggId == id);
        }
    }
}

Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RecipeApp.Data;
using System.Linq;
using System.Threading.Tasks;

namespace RecipeApp.Controllers
{
    public class PostController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PostController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: Post
        public async Task<IActionResult> Index()
        {
            ViewBag.ContainerClass = "pagecontainer";
            return View(await _context.Blogg.OrderByDescending(x => x.CreatedDate).ToListAsync());
        }
        
    }
    
}

Controllers/RecipeController.cs
using Microsoft.AspNetCore.Mvc;

namespace RecipeApp.Controllers
{
    public class RecipeController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.ContainerClass = "pagecontainer";
            return View();
        }

        [Route("produkter")]
        public IActionResult Products()
        {
            ViewBag.ContainerClass = "pagecontainer";
            return View();
        }

        [Route("aterforsaljare")]
        public IActionResult Retailers()
        {
            ViewBag.ContainerClass = "pagecontainer";
            return View();
        }
    }

}

Views/Shared/_AdminHeader.cshtml
@{
}
<header class="mainheader headerback">
    <nav class="mainnav" id="mainnav">
        <ul class="pagenav">
            <li class="hidebig"><a href="javascript:void(0)" class="closebtn hidebig" onclick="closeNav()">&times;</a></li>
            <li class="mainli"><a asp-controller="Blogg" asp-action="Admin">Admin</a></li>
            <li class="mainli"><a asp-controller="Blogg" asp-action="Create">Skapa inlägg</a></li>
            <li class="mainli"><a asp-controller="Blogg" asp-action="Index">Redigera inlägg</a></li>
            <li class="mainli"><a asp-controller="Post" asp-action="Index">Se inlägg</a></li>
        </ul>
        <partial name="_LoginPartial" />
    </nav>
    <span id="menuButton" class="hidebig" role="navigation" onclick="openNav()">&#9776;</span>
</header>

Views/Shared/_FullPageLayout.cshtml
<!DOCTYPE html>
<html lang="sv-se">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Recipe for health : @ViewData["Title"]</title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> -->
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/layout.css" />

</head>
<body>
    <div class="container">
        <div class="firstpage">
            <header class="mainheader">
                <nav class="mainnav" id="mainnav">
                    <ul class="pagenav">
                        <li class="hidebig"><a href="javascript:void(0)" class="closebtn hidebig" onclick="closeNav()">&times;</a></li>
                        <li class="mainli"><a asp-controller="Recipe" asp-action="Index">Startsida</a></li>
                        <li class="mainli"><a asp-controller="Recipe" asp-action="Products">Produkter</a></li>
                        <li class="mainli"><a asp-controller="Recipe" asp-action="Retailers">Återförsäljare</a></li>
                        <li class="mainli"><a asp-controller="Post" asp-action="Index">Blogg</a></li>
                    </ul>
                    <partial name="_LogPartial" />
                </nav>
                <span id="menuButton" class="hidebig" role="navigation" onclick="openNav()">&#9776;</span>
            </header>

            <div class="firstname">
                <h1>Recipe for Health</h1>
            </div>
        </div> 
        
            @RenderBody()

        <footer class="homefooter">
            <div class="footercontent">
                <p class="footer-copywright">&#169; 2020-2021 Recipe for Health Sweden</p>
                <p class="footer-admin-link">
                    <a asp-controller="Blogg" asp-action="Admin">
                        <img alt="Link to admin-page" src="~/images/pill1.png" width="25">
                    </a>
                </p>
            </div>
        </footer>
    </div>

    <script src="~/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="sv-se">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Recipe for health : @ViewData["Title"]</title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> -->
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/layout.css" />

</head>
<body>
    <div class="container @ViewBag.ContainerClass">
        <!-- Check if user is logged in to display different header-->
        @if (User.Identity.IsAuthenticated)
        {
            <partial name="_AdminHeader" />
        }
        else
        {
            <partial name="_header" />
        }
        <main class="main">
            @RenderBody()
        </main>
        <!-- Only display footer if user isn´t logged in -->
        @if (!User.Identity.IsAuthenticated)
        {
            <partial name="_footer" />
        }

    </div>

    <script src="~/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LogPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="loginnav">
@if (SignInManager.IsSignedIn(User))
{
    <li class="mainli">
        <a  asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage"> @User.Identity.Name </a>
    </li>
    <li class="mainli">
        <a asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Recipe", new { area = "" })">
            Logga ut
        </a>
    </li>
}
else
{
}
</ul>

Views/Shared/_footer.cshtml
@{
}
<footer class="mainfooter">
    <div class="footercontent">
        <p>&#169; 2020-2021 Recipe for Health Sweden</p>
    </div>
</footer>

Views/Shared/_header.cshtml
@{
}
<header class="mainheader headerback">
    <nav class="mainnav" id="mainnav">
        <ul class="pagenav">
            <li class="hidebig"><a href="javascript:void(0)" class="closebtn hidebig" onclick="closeNav()">&times;</a></li>
            <li class="mainli"><a asp-controller="Recipe" asp-action="Index">Startsida</a></li>
            <li class="mainli"><a asp-controller="Recipe" asp-action="Products">Produkter</a></li>
            <li class="mainli"><a asp-controller="Recipe" asp-action="Retailers">Återförsäljare</a></li>
            <li class="mainli"><a asp-controller="Post" asp-action="Index">Blogg</a></li>
        </ul>
        <partial name="_LogPartial" />
    </nav>
    <span id="menuButton" class="hidebig" role="navigation" onclick="openNav()">&#9776;</span>

    <div class="header-logo">
        <a asp-controller="Recipe" asp-action="Index">
            <img class="header-image" alt="Logo with text: Recipe for health" src="~/images/logolight.png">
        </a>
    </div>
</header>